Added a pause feature
blueOkiris/tetris-cli pull request #5
Opened 2023-09-05 18:11 UTC by johannptl

Hi there,

I hope you're doing well! I wanted to contribute to this awesome Tetris CLI version because I've become addicted to it. I found myself playing it during boring lectures, and it's been a lifesaver. However, there was one missing feature - a pause function.

In class, when the teacher would approach, I had to pretend to be working, and I often ended up losing my game. As a result, I couldn't set any high scores. To solve this issue, I've added a simple pause function. Now, you can pause the game by pressing the 'P' key.

I hope this improvement makes the game even more enjoyable for everyone.

Happy gaming!

2023-09-06 18:18 UTC, blueOkiris requested changes
Thanks for contributing! Pausing is a good feature to have.

I have a few things I'd like changed as you can see below, but also, can you bump the version number in Cargo.toml/.lock to `23.96.1`?

Thanks!

2023-09-06 18:18 UTC, blueOkiris commented on src/game.rs
> +        let pause_top    = "╔══════╗".to_string();
I would prefer it to use `draw_strs` (see line 270 for an example usage) and then move this to the top as a const like `BORDER` (and also add a space between border and text) :

```
const PAUSE: [&'static str; DISP_HEIGHT as usize] = [
    "╔════════╗",
    "║ PAUSED ║",
    "╚════════╝"
];
```

And then call it via `cnv.draw_strs(&PAUSE.to_vec(), (7, 13), SCORE_COLOR, &Reset)`

2023-09-06 18:18 UTC, blueOkiris commented on src/game.rs
> +                    loop {
Can you make this a while loop?

```
while inp.get_key() != b'p' {
    ...
}
```

Also, the actions in the pause sub-loop are pretty self-explanatory, so there's no need for any comments

2023-09-06 18:18 UTC, blueOkiris commented on src/main.rs
> +    "║    - p -> pause    ║",
Nothing wrong with this, but I wanted to note that the "p for pause" thing should be added to the README as well under the `Controls` header

2023-09-07 08:28 UTC, johannptl commented
Thanks for the advice. I changed everything now. Sorry for my unclean code.

2023-09-07 16:16 UTC, blueOkiris requested changes
Sorry. One last little thing.

2023-09-07 16:16 UTC, blueOkiris commented on src/main.rs
> +    "                      ",
Can you remove this extra comma here?

2023-09-07 18:56 UTC, johannptl commented
I did. Sorry for that one, my bad.

2023-09-08 19:38 UTC, blueOkiris commented
Alright everything looks good I think. Thanks for the help!

2023-09-08 19:39 UTC, blueOkiris approved these changes

2023-09-08 19:39 UTC, merged